"""Wires up the Google Services Gradle plugin (needed for Firebase Cloud
Messaging / push notifications) in a freshly `flutter create`d Android
project, using the modern declarative plugins{} DSL (the pattern this
Flutter version's template already uses — confirmed by dumping the real
generated settings.gradle.kts/build.gradle.kts from a CI run rather than
assuming, same approach used for every other gradle patch in this
project).

Two files need the plugin declared:
- android/settings.gradle.kts: the version is declared here, once,
  `apply false` (not actually applied at the root, just registered so
  module-level files can apply it without re-specifying a version).
- android/app/build.gradle.kts: applies it for real (no version here —
  resolved via settings.gradle.kts).

google-services.json itself is copied in by a separate, earlier CI step
(it lives at .github/config/google-services.json in this repo, not
inside android/ — that whole directory is regenerated by `flutter
create` on every run, so anything inside it needs to be re-placed by a
script every time, same as this).
"""

SETTINGS_PATH = "android/settings.gradle.kts"
APP_BUILD_PATH = "android/app/build.gradle.kts"
GOOGLE_SERVICES_VERSION = "4.5.0"


def main() -> None:
    with open(SETTINGS_PATH, encoding="utf-8") as f:
        settings = f.read()

    if "com.google.gms.google-services" not in settings:
        marker = 'id("org.jetbrains.kotlin.android") version "2.3.20" apply false'
        if marker not in settings:
            raise SystemExit(
                f"Expected kotlin.android plugin line not found in {SETTINGS_PATH} "
                "(template may have changed format) — refusing to guess where to insert."
            )
        settings = settings.replace(
            marker,
            f'{marker}\n    id("com.google.gms.google-services") version "{GOOGLE_SERVICES_VERSION}" apply false',
        )
        with open(SETTINGS_PATH, "w", encoding="utf-8") as f:
            f.write(settings)
        print(f"Registered com.google.gms.google-services {GOOGLE_SERVICES_VERSION} in {SETTINGS_PATH}")
    else:
        print(f"google-services already registered in {SETTINGS_PATH}, nothing to do.")

    with open(APP_BUILD_PATH, encoding="utf-8") as f:
        app_build = f.read()

    if "com.google.gms.google-services" not in app_build:
        marker = 'id("dev.flutter.flutter-gradle-plugin")'
        if marker not in app_build:
            raise SystemExit(
                f"Expected flutter-gradle-plugin line not found in {APP_BUILD_PATH} "
                "(template may have changed format) — refusing to guess where to insert."
            )
        app_build = app_build.replace(
            marker,
            f'{marker}\n    id("com.google.gms.google-services")',
        )
        with open(APP_BUILD_PATH, "w", encoding="utf-8") as f:
            f.write(app_build)
        print(f"Applied com.google.gms.google-services in {APP_BUILD_PATH}")
    else:
        print(f"google-services already applied in {APP_BUILD_PATH}, nothing to do.")


if __name__ == "__main__":
    main()
